spring:
  config:
    activate:
      on-profile: test

knife4j:
  enable: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoint:
    health:
      show-details: never
