spring:
  config:
    activate:
      on-profile: prod
  flyway:
    clean-disabled: true

knife4j:
  enable: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoint:
    health:
      show-details: never

logging:
  structured:
    format:
      console: ${LOG_STRUCTURED_FORMAT:ecs}
